version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: novaria_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: hospassword
      POSTGRES_DB: novaria_hospital
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: